### ISSUE TITLE
Compiling prequisites on Linux (Ubuntu)

### ISSUE THREAD

**Issue by oberling** [TheSlowGrowth/VCOTuner#10]
Before getting it compiled under Linux (Ubuntu for example) you have to at least install:
`sudo apt-get install build-essential libxcursor-dev libx11-dev libxinerama-dev libxrandr-dev libfreetype6-dev`
You may add this to some readme for linux compiling
Then it compiles and starts. I haven't however tested if everything is working as expected. At least it detects sound cards.
It throws some
`JUCE Assertion failure in juce_AudioSampleBuffer.h:91`
however... but maybe that's normal before having started any audio processing...

**Comment by TheSlowGrowth** [comment]
Yes, the assertion failure has been fixed. See #8 for details. You can check out the features/linux_support branch where we try to fix all linux related problems.

Thanks for trying it out and putting together the list of prerequisites. I'll add a little readme file. Please note that for the latest commit from features/linux_support you will also need libjack-dev.

**Comment by TheSlowGrowth** [comment]
Please let me know if the application works for you. If all is fine on your side, I'll make a new release.
