### ISSUE TITLE
Crashes when trying to save the report on linux

### ISSUE THREAD

**Issue by TheSlowGrowth** [TheSlowGrowth/VCOTuner#11]
The application crashes when the user tries to save the report on a linux OS. The Projucer also hangs when trying to open a file dialog. Apparently this is related to [the bug mentioned in this thread](https://forum.juce.com/t/cant-get-jucer-to-open-files-on-linux/13534/8).

A workaround could be to disable the native file chooser on linux hosts and use the Juce builtin file chooser.

**Comment by Grumskiz** [comment]
The workaround works for me. I can now save reports and even overwrite them.
However the file dialog does not append the .png suffix to the file names automatically.

**Comment by TheSlowGrowth** [comment]
Thanks for the feedback. The file extension should now be automatically added.
