### ISSUE TITLE
Linux (Debian Jessie x86_64) Build Fails

### ISSUE THREAD

**Issue by oblivionratula** [TheSlowGrowth/VCOTuner#24]
I followed the instructions in the file  CompileOnLinux and installed the needed packages.

At first the compile failed at:

> In file included from ../../JuceLibraryCode/juce_audio_devices.cpp:9:0:
../../JuceLibraryCode/modules/juce_audio_devices/juce_audio_devices.cpp:107:30: fatal error: alsa/asoundlib.h: No such file or directory
   #include <alsa/asoundlib.h>
                              ^
compilation  terminated

So I did:

> sudo apt-get install libasound2-dev

^^^ This probably needs to be added to the CompileOnLinux doc

Compile proceeds past this point now, but then stops again at:

> Compiling juce_graphics.cpp
> In file included from ../../JuceLibraryCode/juce_graphics.cpp:9:0:
> ../../JuceLibraryCode/modules/juce_graphics/juce_graphics.cpp:93:24: fatal error: ft2build.h: No such file or directory
>    #include <ft2build.h>
>                         ^
> compilation terminated.
 
Searching http://packages.debian.org, it seems libfreetype6-dev is what is needed, but even with that installed (per the CompileOnLinux instructions), it's no joy.

I made sure to apt-get update/upgrade and try again, but it still fails. 

It looks like the file moved to:

> /usr/include/freetype2/ft2build.h

I tried editing JuceLibraryCode/modules/juce_graphics/juce_graphics.cpp and prepending 'freetype2/' on the include line for ft2build.h but that lead to other problems (the config/ftheader.h path wasn't right). I know just enough to know I don't know how to properly fix this, but would like to help.

**Comment by TheSlowGrowth** [comment]
Have you tried to add the include path for freetype manually in the makefile?
To be honest, I'm not sure what's wrong here. It always worked for me straight away. Maybe you can find more help in the JUCE documentation - it is a JUCE related problem.

**Comment by oblivionratula** [comment]
I looked at that possibility, but honestly don't know how or where to do that. If I have time to tinker I'll try to figure it out.

**Comment by oblivionratula** [comment]
Got it to build with "-I/usr/include/freetype2" appended to JUCE_CPPFLAGS line in Makefile. 

I made a pull request with this change, but don't know if it needs to be a universal change or is better off as a note in the CompileOnLinux file.  Also, hoping I'm doing these forks/edits/branches/pull requests correctly.  It's the first time I've used git for more than just myself.

**Comment by oblivionratula** [comment]
Built OK with new changes.  Closing.  Thanks.
