### ISSUE TITLE
Audio input selection only shows output devices

### ISSUE THREAD

**Issue by Grumskiz** [TheSlowGrowth/VCOTuner#8]
The Audio Settings only list output devices in the selection menu for an input device.
The standard selection is:

> Default ALSA Output (Currently PulseAudio Sound Server)

Another option is:

> iO4, USB Audio; Front Speakers

But there are no input devices available.

I also get the following assertion failure repeating while running the program:

> JUCE Assertion failure in juce_AudioSampleBuffer.h:91

This stops when I select "None" as an input device.

The line of code it points to reads:
`jassert(dataToReferTo != nullptr);`

I am running the tool on Arch Linux and tried using PulseAudio and Jack as a soundserver, without change.
Compilation did not raise any warnings or errors. MIDI Device Selection seems to work, but so far I couldn't get the tool to output any MIDI messages.

**Comment by TheSlowGrowth** [comment]
Thanks for reporting this.
I've compiled it under ubuntu 16.04 and I'm getting the same assertion failure. 

I can select "Playback/Recording through the PulseAudio soundserver" as the device and according to the level meter I get the microphone signal (I'm running this in a virtualbox on an OSX host).

**Comment by TheSlowGrowth** [comment]
The assertion failure should be gone with commit 7c508f1065cc5c8ffe3c4c7940c84ccfe3ca1efb in the features/linux_support branch

**Comment by Grumskiz** [comment]
Yes, the assertion failure has disappeared.
I still only have output devices in the list. They are either completely silent or always clipped.

**Comment by TheSlowGrowth** [comment]
That's weird. I'm using a builtin class for this, juce::AudioDeviceSelectorComponent. You can see the initialization in MainComponent.cpp:224. I'm telling it that I need a minimum and maximum of 1 audio inputs and no audio outputs.
Can you try to build any of the juce example projects? There are simple audio projects as well. They use the same device selector class. Does the error appear there as well?

**Comment by Grumskiz** [comment]
Yeah, I have looked up the AudieDeviceSelectorComponent in the Juce API and can't find anything wrong with it. I tried to activate outputs as well, but that only gives me two dropdown menus with only output devices.

I'm compiling the juce examples right now and will report back.

Edit:
Compiling the examples doesn't work. I did it manuall as the Projucer doesn't really work either. It just says "Linux Support is still under development".

**Comment by TheSlowGrowth** [comment]
I build the Projucer on my ubuntu VM and it starts but hangs when I try to open a project. I was able to build the audio plugin host demo, but I get a memory access error when launching it. BTW I'm using Juce 4.2.2 here.
Did you manage to compile the audio plugin host demo? You have to edit the VST3 SDK folder path in the makefile so no Projucer is needed to get this to compile. If it runs on your system, you can try to route audio inputs to audio outputs to see if the device handling works there.

**Comment by Grumskiz** [comment]
Looks like I found a fix!
I activated JACK Support in the AppConfig.h in the JuceLibraryCode Folder. Now I can select the JACK audio server in the Setup menu and then select an input device. I have no idea why it doesn't work with ALSA.

My change is in line 75 of AppConfig.h:
Old:
`//#define JUCE_JACK`
New:
`#define JUCE_JACK 1`

This produces a slight cosmetic fault:
The settings window is now normally too small to show all options, but one can still manually resize the window.

I can't compile any of the JUCE demos because there seems to be a problem with the FLAC format module. I haven't bothered looking into that.

**Comment by TheSlowGrowth** [comment]
> but one can still manually resize the window.

Actually, that was disabled until now. I don't know why it worked for you. Ahh, juce's linux support doesn't seem to be as good as it could be...

Thanks for the suggestion with Jack. As most audio people will use jack anyway, I thinks its a good idea to enable it by default. I've done so and pushed the changes. The settings window should also be large enough now and it is set to be resizable as well.

Does the application work for you now?

**Comment by Grumskiz** [comment]
I have only done some quick tests yesterday. So far everything seems to work, except saving the PNG report, though it shows up in the window. I think this is another JUCE problem, as I can't open any file dialogs in the Projucer either.

**Comment by TheSlowGrowth** [comment]
I've added #11 to fix the file chooser dialog problems. 
It seems like this issue here is resolved now. Cool :-)
